require("modules.monitors")
require("modules.keybinds")
require("modules.autostart")
require("modules.env")
require("modules.permissions")
require("modules.animations")
require("modules.window-rules")
